export const ESTADOS_SOLICITUD = {
  PENDIENTE: 'PENDIENTE',
  APROBADA: 'APROBADA',
  RECHAZADA: 'RECHAZADA',
};

export const ESTADOS_LABELS = {
  PENDIENTE: 'Pendiente',
  APROBADA: 'Aprobada',
  RECHAZADA: 'Rechazada',
};

export const ESTADOS_COLORES = {
  PENDIENTE: '#ff9800',
  APROBADA: '#4caf50',
  RECHAZADA: '#f44336',
};

export const TIPOS_SOLICITUD = {
  DESPLIEGUE: 'DESPLIEGUE',
  ACCESO: 'ACCESO',
  CAMBIO_TECNICO: 'CAMBIO_TECNICO',
  CAMBIO_PIPELINE: 'CAMBIO_PIPELINE',
  INCORPORACION_HERRAMIENTA: 'INCORPORACION_HERRAMIENTA',
};

export const TIPOS_SOLICITUD_LABELS = {
  DESPLIEGUE: 'Despliegue',
  ACCESO: 'Acceso a Herramientas',
  CAMBIO_TECNICO: 'Cambio Técnico',
  CAMBIO_PIPELINE: 'Cambio en Pipeline',
  INCORPORACION_HERRAMIENTA: 'Incorporación de Herramienta',
};

export const ROLES_USUARIO = {
  SOLICITANTE: 'SOLICITANTE',
  APROBADOR: 'APROBADOR',
  ADMINISTRADOR: 'ADMINISTRADOR',
};